name: flutter_boolean_template
description: An opinionated template for a Flutter project.

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0 <4.0.0"

dependency_overrides:
  test_api: ">=0.6.0 <0.7.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_native_splash: ^2.3.8
  hooks_riverpod: ^2.4.9
  riverpod_annotation: ^2.2.0
  flutter_flavor: ^3.1.1
  fpdart: ^1.1.0
  stock: ^1.0.1
  flex_color_scheme: ^7.3.1
  flutter_hooks: ^0.20.3
  dart_mappable: ^4.1.0
  http: ^1.1.2
  riverpod: ^2.3.6
  modddels_annotation_fpdart: ^0.2.0
  freezed_annotation: ^2.2.0
  localization:
    path: packages/localization
  env:
    path: packages/env
  assets:
    path: packages/assets
  log:
    path: packages/log
  constants:
    path: packages/constants
  adaptive_breakpoints: ^0.1.6
  google_fonts: ^6.1.0
  settings_ui: ^2.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  universal_html: ^2.2.4
  window_manager: ^0.3.7
  go_router:
    git:
      url: https://github.com/getBoolean/flutter_packages
      ref: feature/go_router_title_builder
      path: packages/go_router
  awesome_flutter_extensions: ^1.2.0
  collection: ^1.18.0

dev_dependencies:
  flutter_lints: ^3.0.1
  custom_lint: ^0.5.7
  riverpod_lint: ^2.1.1
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  build_verify: ^3.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  melos: ^3.4.0
  msix: ^3.16.7
  mason: ^0.1.0-dev.51
  patrol: ^3.1.0
  dart_mappable_builder: ^4.1.0
  mocktail: ^1.0.1
  test: any
  modddels: ^0.2.0
  freezed: ^2.3.5
  change_app_package_name: ^1.1.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

msix_config:
  display_name: Flutter Template App
  install_certificate: false

patrol:
  app_name: Flutter Boolean Template
  android:
    package_name: com.example.flutter_boolean_template
  ios:
    bundle_id: com.example.flutterBooleanTemplate
